/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Guia5A;

import com.sun.j3d.loaders.IncorrectFormatException;
import com.sun.j3d.loaders.ParsingErrorException;
import com.sun.j3d.utils.behaviors.mouse.MouseBehavior;
import com.sun.j3d.utils.behaviors.mouse.MouseRotate;
import com.sun.j3d.utils.universe.SimpleUniverse;
import java.awt.GraphicsConfiguration;
import java.io.FileNotFoundException;
import javax.media.j3d.AmbientLight;
import javax.media.j3d.Background;
import javax.media.j3d.BoundingSphere;
import javax.media.j3d.BranchGroup;
import javax.media.j3d.Canvas3D;
import javax.media.j3d.DirectionalLight;
import javax.media.j3d.GeometryArray;
import javax.media.j3d.IndexedQuadArray;
import javax.media.j3d.Shape3D;
import javax.media.j3d.Transform3D;
import javax.media.j3d.TransformGroup;
import javax.vecmath.Color3f;
import javax.vecmath.Point3d;
import javax.vecmath.Point3f;
import javax.vecmath.Vector3d;
import javax.vecmath.Vector3f;
import org.jdesktop.j3d.loaders.vrml97.VrmlLoader;

/**
 *
 * @author Yery Pedraza
 */
public class Ejercicio extends javax.swing.JApplet {

    private SimpleUniverse simpleu=null;
    private TransformGroup obj1, obj2, obj3, obj4, obj5, obj6, obj7;
    
    @Override
    public void init() {
       
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    GraphicsConfiguration config = SimpleUniverse.getPreferredConfiguration();
                    Canvas3D canvas3D = new Canvas3D(config);
                    
                    PVisual.add("Center", canvas3D);
                    
                    BranchGroup scene = createSceneGraph();
                    scene.compile();
                    
                    simpleu = new SimpleUniverse(canvas3D);
                    simpleu.getViewingPlatform().setNominalViewingTransform();
                    simpleu.addBranchGraph(scene);
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PVisual = new javax.swing.JPanel();
        PControl = new javax.swing.JPanel();
        Figura1 = new javax.swing.JPanel();
        Xpositivo = new javax.swing.JButton();
        XNegativo = new javax.swing.JButton();
        Figura2 = new javax.swing.JPanel();
        Ypositivof2 = new javax.swing.JButton();
        Ynegativof2 = new javax.swing.JButton();
        Figura3 = new javax.swing.JPanel();
        Ypositivof3 = new javax.swing.JButton();
        Ynegativof3 = new javax.swing.JButton();
        Figura5 = new javax.swing.JPanel();
        Ypositivof5 = new javax.swing.JButton();
        Ynegativof5 = new javax.swing.JButton();
        Rotacion = new javax.swing.JButton();
        Camera = new javax.swing.JPanel();
        Acercamiento = new javax.swing.JButton();
        Alejamiento = new javax.swing.JButton();

        javax.swing.GroupLayout PVisualLayout = new javax.swing.GroupLayout(PVisual);
        PVisual.setLayout(PVisualLayout);
        PVisualLayout.setHorizontalGroup(
            PVisualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        PVisualLayout.setVerticalGroup(
            PVisualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Figura1.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimiento 1"));

        Xpositivo.setText("Izquierda");
        Xpositivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XpositivoActionPerformed(evt);
            }
        });

        XNegativo.setText("Derecha");
        XNegativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XNegativoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Figura1Layout = new javax.swing.GroupLayout(Figura1);
        Figura1.setLayout(Figura1Layout);
        Figura1Layout.setHorizontalGroup(
            Figura1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Figura1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Xpositivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(XNegativo)
                .addContainerGap())
        );

        Figura1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {XNegativo, Xpositivo});

        Figura1Layout.setVerticalGroup(
            Figura1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Figura1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(Figura1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Xpositivo)
                    .addComponent(XNegativo))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        Figura2.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimiento 2"));

        Ypositivof2.setText("Arriba");
        Ypositivof2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ypositivof2ActionPerformed(evt);
            }
        });

        Ynegativof2.setText("Abajo");
        Ynegativof2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ynegativof2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Figura2Layout = new javax.swing.GroupLayout(Figura2);
        Figura2.setLayout(Figura2Layout);
        Figura2Layout.setHorizontalGroup(
            Figura2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Figura2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ypositivof2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ynegativof2)
                .addContainerGap())
        );

        Figura2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Ynegativof2, Ypositivof2});

        Figura2Layout.setVerticalGroup(
            Figura2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Figura2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(Figura2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ypositivof2)
                    .addComponent(Ynegativof2))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        Figura3.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimiento 3"));

        Ypositivof3.setText("Arriba");
        Ypositivof3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ypositivof3ActionPerformed(evt);
            }
        });

        Ynegativof3.setText("Abajo");
        Ynegativof3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ynegativof3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Figura3Layout = new javax.swing.GroupLayout(Figura3);
        Figura3.setLayout(Figura3Layout);
        Figura3Layout.setHorizontalGroup(
            Figura3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Figura3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ypositivof3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ynegativof3)
                .addContainerGap())
        );

        Figura3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Ynegativof3, Ypositivof3});

        Figura3Layout.setVerticalGroup(
            Figura3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Figura3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Figura3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ypositivof3)
                    .addComponent(Ynegativof3))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        Figura5.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimiento 5"));

        Ypositivof5.setText("Arriba");
        Ypositivof5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ypositivof5ActionPerformed(evt);
            }
        });

        Ynegativof5.setText("Abajo");
        Ynegativof5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ynegativof5ActionPerformed(evt);
            }
        });

        Rotacion.setText("Rotación");
        Rotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Figura5Layout = new javax.swing.GroupLayout(Figura5);
        Figura5.setLayout(Figura5Layout);
        Figura5Layout.setHorizontalGroup(
            Figura5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Figura5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ypositivof5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ynegativof5)
                .addContainerGap())
            .addGroup(Figura5Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(Rotacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Figura5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Rotacion, Ynegativof5, Ypositivof5});

        Figura5Layout.setVerticalGroup(
            Figura5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Figura5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Figura5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ypositivof5)
                    .addComponent(Ynegativof5))
                .addGap(18, 18, 18)
                .addComponent(Rotacion)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        Camera.setBorder(javax.swing.BorderFactory.createTitledBorder("Cámara"));

        Acercamiento.setText("+");
        Acercamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercamientoActionPerformed(evt);
            }
        });

        Alejamiento.setText("-");
        Alejamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlejamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CameraLayout = new javax.swing.GroupLayout(Camera);
        Camera.setLayout(CameraLayout);
        CameraLayout.setHorizontalGroup(
            CameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CameraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Acercamiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Alejamiento)
                .addContainerGap())
        );

        CameraLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Acercamiento, Alejamiento});

        CameraLayout.setVerticalGroup(
            CameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CameraLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(CameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Acercamiento)
                    .addComponent(Alejamiento))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PControlLayout = new javax.swing.GroupLayout(PControl);
        PControl.setLayout(PControlLayout);
        PControlLayout.setHorizontalGroup(
            PControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Figura1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Figura2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Figura3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Figura5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Camera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PControlLayout.setVerticalGroup(
            PControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Figura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Figura2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Figura3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Figura5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Camera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PVisual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PVisual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private BranchGroup createSceneGraph(){
    
        BranchGroup objRoot = new BranchGroup();
        
        obj1 = new TransformGroup();
        obj1.setCapability(TransformGroup.ALLOW_TRANSFORM_READ);
        obj1.setCapability(TransformGroup.ALLOW_TRANSFORM_WRITE);
        
        obj2 = new TransformGroup();
        obj2.setCapability(TransformGroup.ALLOW_TRANSFORM_READ);
        obj2.setCapability(TransformGroup.ALLOW_TRANSFORM_WRITE);
        
        obj3 = new TransformGroup();
        obj3.setCapability(TransformGroup.ALLOW_TRANSFORM_READ);
        obj3.setCapability(TransformGroup.ALLOW_TRANSFORM_WRITE);
        
        obj4 = new TransformGroup();
        obj4.setCapability(TransformGroup.ALLOW_TRANSFORM_READ);
        obj4.setCapability(TransformGroup.ALLOW_TRANSFORM_WRITE);
        
        obj5 = new TransformGroup();
        obj5.setCapability(TransformGroup.ALLOW_TRANSFORM_READ);
        obj5.setCapability(TransformGroup.ALLOW_TRANSFORM_WRITE);

        obj6 = new TransformGroup();
        obj6.setCapability(TransformGroup.ALLOW_TRANSFORM_READ);
        obj6.setCapability(TransformGroup.ALLOW_TRANSFORM_WRITE);
        
        obj7 = new TransformGroup();
        obj7.setCapability(TransformGroup.ALLOW_TRANSFORM_READ);
        obj7.setCapability(TransformGroup.ALLOW_TRANSFORM_WRITE);
        
        obj1.addChild(loadGeometryWRL("brazoparte1.wrl"));
        
        /*obj2.addChild(loadGeometryWRL("brazoparte2.wrl"));
        obj1.addChild(obj2);
        
        obj3.addChild(loadGeometryWRL("brazoparte3.wrl"));
        obj1.addChild(obj3);
        obj2.addChild(obj3);
        
        obj4.addChild(loadGeometryWRL("brazoparte4.wrl"));
        obj1.addChild(obj4);
        obj2.addChild(obj4);
        obj3.addChild(obj4);
        
        obj5.addChild(loadGeometryWRL("brazoparte5.wrl"));
        obj1.addChild(obj5);
        obj2.addChild(obj5);
        obj3.addChild(obj5);
        obj4.addChild(obj5);
        
        obj6.addChild(loadGeometryWRL("brazoparte6.wrl"));
        obj1.addChild(obj6);
        obj2.addChild(obj6);
        obj3.addChild(obj6);
        obj4.addChild(obj6);
        obj5.addChild(obj6);
        
        obj7.addChild(loadGeometryWRL("brazoparte7.wrl"));
        obj1.addChild(obj7);
        obj2.addChild(obj7);
        obj3.addChild(obj7);
        obj4.addChild(obj7);
        obj5.addChild(obj7);
        obj6.addChild(obj7);*/
        
        //luces
        objRoot.addChild(luces());
        
        //fondo
        objRoot.addChild(fondo());
        
        //piso
        objRoot.addChild(piso());
        
        return objRoot;
    }
    
    public BranchGroup loadGeometryWRL(String geometryURL){
    BranchGroup objLoad = new BranchGroup();
    
    VrmlLoader wrl = new VrmlLoader();
        try {
            objLoad = wrl.load(geometryURL).getSceneGroup();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (ParsingErrorException ex) {
            ex.printStackTrace();
        } catch (IncorrectFormatException ex) {
            ex.printStackTrace();
        }
        return objLoad;
    }
    
    private TransformGroup fondo(){
    TransformGroup objRoot = new TransformGroup();
    
    Background font = new Background(new Color3f(0.5f, 0.6f, 0.9f));
    
    font.setApplicationBounds(new BoundingSphere(new Point3d(), 100.0));
    
    objRoot.addChild(font);
    
    return objRoot;
    }
    
    private TransformGroup luces(){
    TransformGroup objRoot = new TransformGroup();
    
    BoundingSphere bounds = new BoundingSphere(new Point3d(0,0,5), 100.0);
    Color3f lightColor = new Color3f(1.0f, 1.0f, 1.0f);
    Vector3f lightDirection = new Vector3f(0.0f, -1.0f, -1f);
    
    DirectionalLight luz1 = new DirectionalLight(lightColor, lightDirection);
    luz1.setInfluencingBounds(bounds);
    objRoot.addChild(luz1);
    
    AmbientLight luz2 = new AmbientLight(lightColor);
    luz2.setInfluencingBounds(bounds);
    objRoot.addChild(luz2);
        
    return objRoot;
    }
    
    private TransformGroup piso(){
    TransformGroup sueloTransf = new TransformGroup();
    
    int tamano = 100;
    Point3f[] vertices = new Point3f[tamano * tamano];
    
    float inicio = -20.0f;
    float x = inicio;
    float z = inicio;
    
    float salto = 1.0f;
    
    int[] indices = new int[(tamano - 1) * (tamano - 1) * 4];
    int n = 0;
    
    Color3f blanco = new Color3f(1.0f, 1.0f, 1.0f);
    Color3f negro = new Color3f(0.5f, 0.0f, 0.0f);
    Color3f[] colors = {blanco, negro};
    
    int[] colorindices = new int[indices.length];
    
            for (int i = 0; i < tamano; i++) {
            for (int j = 0; j < tamano; j++) {
                vertices[i * tamano + j] = new Point3f(x, -1.0f, z);
                z += salto;
                if (i < (tamano - 1) && j < (tamano - 1)) {
                    int cindex = (i % 2 + j) % 2;
                    colorindices[n] = cindex;
                    indices[n++] = i * tamano + j;
                    colorindices[n] = cindex;
                    indices[n++] = i * tamano +
                            (j + 1);
                    colorindices[n] = cindex;
                    indices[n++] = (i + 1) *
                            tamano + (j + 1);
                    colorindices[n] = cindex;
                    indices[n++] = (i + 1) *
                            tamano + j;
                }
            }
            z = inicio;
            x += salto;
        }
            
    IndexedQuadArray geom = new IndexedQuadArray(vertices.length,
            GeometryArray.COORDINATES |
            GeometryArray.COLOR_3,
            indices.length);
    
    geom.setCoordinates(0, vertices);
    geom.setCoordinateIndices(0, indices);
    geom.setColors(0, colors);
    geom.setColorIndices(0, colorindices);
    
    Shape3D suelo = new Shape3D(geom);
    sueloTransf.addChild(suelo);
            
    return sueloTransf;
    }
    
    private void Ynegativof3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ynegativof3ActionPerformed

    Transform3D actual = new Transform3D();
    obj4.getTransform(actual);
    Transform3D inc = new Transform3D();
    inc.rotX(Math.PI / 16);
    actual.mul(inc);
    obj4.setTransform(actual);
        // TODO add your handling code here:
    }//GEN-LAST:event_Ynegativof3ActionPerformed

    private void XpositivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XpositivoActionPerformed

    Transform3D actual = new Transform3D();
    obj2.getTransform(actual);
    Transform3D inc = new Transform3D();
    inc.rotY(-Math.PI / 16);
    actual.mul(inc);
    obj2.setTransform(actual);

    }//GEN-LAST:event_XpositivoActionPerformed

    private void AcercamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercamientoActionPerformed

        TransformGroup universo = simpleu.getViewingPlatform().getViewPlatformTransform();
        
        Transform3D actual = new Transform3D();
        universo.getTransform(actual);
       
        Transform3D inc = new Transform3D();
        inc.set(new Vector3d(0,0,0.1));
    
        actual.mul(inc);
    
        universo.setTransform(actual);
                       
    }//GEN-LAST:event_AcercamientoActionPerformed

    private void AlejamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlejamientoActionPerformed

    TransformGroup universo =
    simpleu.getViewingPlatform().getViewPlatformTransform();
    
  
    Transform3D actual = new Transform3D();
    universo.getTransform(actual);
    
   
    Transform3D inc = new Transform3D();
    inc.set(new Vector3d(0,0,-0.1));
 
    actual.mul(inc);
    
    universo.setTransform(actual);
  
    }//GEN-LAST:event_AlejamientoActionPerformed

    private void XNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XNegativoActionPerformed

    Transform3D actual = new Transform3D();
    obj2.getTransform(actual);
    Transform3D inc = new Transform3D();
    inc.rotY(Math.PI / 16);
    actual.mul(inc);
    obj2.setTransform(actual);


    }//GEN-LAST:event_XNegativoActionPerformed

    private void Ypositivof2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ypositivof2ActionPerformed

    Transform3D actual = new Transform3D();
    obj3.getTransform(actual);
    Transform3D inc = new Transform3D();
    inc.rotX(-Math.PI / 16);
    actual.mul(inc);
    obj3.setTransform(actual);
  
    }//GEN-LAST:event_Ypositivof2ActionPerformed

    private void Ypositivof3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ypositivof3ActionPerformed

    Transform3D actual = new Transform3D();
    obj4.getTransform(actual);
    Transform3D inc = new Transform3D();
    inc.rotX(-Math.PI / 16);
    actual.mul(inc);
    obj4.setTransform(actual);

        // TODO add your handling code here:
    }//GEN-LAST:event_Ypositivof3ActionPerformed

    private void Ynegativof2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ynegativof2ActionPerformed

    Transform3D actual = new Transform3D();
    obj3.getTransform(actual);
    Transform3D inc = new Transform3D();
    inc.rotX(Math.PI / 16);
    actual.mul(inc);
    obj3.setTransform(actual);
        // TODO add your handling code here:
    }//GEN-LAST:event_Ynegativof2ActionPerformed

    private void Ynegativof5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ynegativof5ActionPerformed

    Transform3D actual = new Transform3D();
    obj1.getTransform(actual);
    Transform3D inc = new Transform3D();
    inc.rotX(Math.PI / 16);
    actual.mul(inc);
    obj1.setTransform(actual);
        // TODO add your handling code here:
    }//GEN-LAST:event_Ynegativof5ActionPerformed

    private void RotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotacionActionPerformed

    Transform3D actual = new Transform3D();
    obj6.getTransform(actual);
    Transform3D inc = new Transform3D();
    inc.rotZ(-Math.PI / 16);
    actual.mul(inc);
    obj6.setTransform(actual);
        // TODO add your handling code here:
    }//GEN-LAST:event_RotacionActionPerformed

    private void Ypositivof5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ypositivof5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ypositivof5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acercamiento;
    private javax.swing.JButton Alejamiento;
    private javax.swing.JPanel Camera;
    private javax.swing.JPanel Figura1;
    private javax.swing.JPanel Figura2;
    private javax.swing.JPanel Figura3;
    private javax.swing.JPanel Figura5;
    private javax.swing.JPanel PControl;
    private javax.swing.JPanel PVisual;
    private javax.swing.JButton Rotacion;
    private javax.swing.JButton XNegativo;
    private javax.swing.JButton Xpositivo;
    private javax.swing.JButton Ynegativof2;
    private javax.swing.JButton Ynegativof3;
    private javax.swing.JButton Ynegativof5;
    private javax.swing.JButton Ypositivof2;
    private javax.swing.JButton Ypositivof3;
    private javax.swing.JButton Ypositivof5;
    // End of variables declaration//GEN-END:variables
}
